### PR TITLE
Branch quiz feature

### LINKED ISSUE #134: As a Primary 6 student, I can take and review Mathematics MCQ quizzes
... so that I can practice for my exams, and be able to review where I went wrong.

### PR DESCRIPTION
**Pull request by elizabethcwt**
Fixes #134

### CODE REVIEW

File: src/main/java/seedu/duke/model/quiz/Quiz.java [hunk 1]
```diff
@@ -70,26 +70,47 @@ public String convertToData() {
...
-        return question + "\n"
+        return question + "\n\n"
                 + "(1) " + option1 + "\n"
                 + "(2) " + option2 + "\n"
                 + "(3) " + option3 + "\n"
-                + "(4) " + option4 + "\n";
+                + "(4) " + option4 + "\n\n";
+    }
+
+    public String printPostQuizQuestion(int l) {
```
Comment (durianpancakes) [inline src/main/java/seedu/duke/model/quiz/Quiz.java]: public String printPostQuizQuestion(int l, String correctnessLogo) {

File: src/main/java/seedu/duke/model/quiz/Quiz.java [hunk 2]
```diff
@@ -70,26 +70,47 @@ public String convertToData() {
...
+        if (explanation.equals("")) {
+            return question + QuizManager.correctnessLogo + "\n\n"
```
Comment (durianpancakes) [inline src/main/java/seedu/duke/model/quiz/Quiz.java]: return question + correctnessLogo + "\n\n"

File: src/main/java/seedu/duke/model/quiz/Quiz.java [hunk 3]
```diff
@@ -70,26 +70,47 @@ public String convertToData() {
...
+                    + "(1) " + option1 + "\n"
+                    + "(2) " + option2 + "\n"
+                    + "(3) " + option3 + "\n"
+                    + "(4) " + option4 + "\n\n"
+                    + "Your answer: " + l + "\n"
+                    + "Correct answer: " + answer + "\n\n";
+        } else {
+            return question + QuizManager.correctnessLogo + "\n\n"
```
Comment (durianpancakes) [inline src/main/java/seedu/duke/model/quiz/Quiz.java]: return question + correctnessLogo + "\n\n"

File: src/main/java/seedu/duke/model/quiz/QuizManager.java [hunk 4]
```diff
@@ -102,9 +93,24 @@ public void takeQuiz(String[] separatedInputs) {
                         }
                     }
 
-                    // TODO Print results, questions, user's answers, correct answers and explanations
-                    System.out.println("\nYou scored " + correctCounter + " out of " + noOfQues + "!\n");
+                    for (int l = 0; l < noOfQues; l++) {
 
+                        // Assigning the correctness logo to be printed with questions post-quiz
```
Comment (durianpancakes) [inline src/main/java/seedu/duke/model/quiz/QuizManager.java:99]: Add one line here:

String correctnessLogo;

File: src/main/java/seedu/duke/model/quiz/QuizManager.java [hunk 5]
```diff
@@ -102,9 +93,24 @@ public void takeQuiz(String[] separatedInputs) {
...
+                        if (userAnswerManager.getCorrectness().get(l).equals(true)) {
+                            correctnessLogo = " [CORRECT ☺︎]";
+                        } else {
+                            correctnessLogo = " [WRONG ☹︎]";
+                        }
+
+                        // Print out all quiz questions, user's answers, correctness, correct answers and explanations
+                        System.out.println("Question " + (l + 1) + ": ");
+                        System.out.println(quizzes.get(quizIndexes.get(l)).printPostQuizQuestion(userAnswerManager.
```
Comment (durianpancakes) [inline src/main/java/seedu/duke/model/quiz/QuizManager.java]: System.out.println(quizzes.get(quizIndexes.get(l)).printPostQuizQuestion(userAnswerManager.
                                getUserAnswers().get(l), correctnessLogo));

**Review by durianpancakes — DISMISSED** [review]
Verified with your repository that the changes are working.
